### ISSUE TITLE
Подключение Vakio к MQTT брокеру из локальной сети

### ISSUE THREAD

**Issue by kolhozz** [vakio-ru/vakio-public-api#11]
Помогите разобраться, может я что-то делаю не так.

Возникла следующая проблема vakio base smart꞉
при подключении к моей wifi сети, vakio не находит mqtt брокер, хотя он установлен и к нему есть доступ.

![photo_2023-10-20 13 29 43](https://github.com/vakio-ru/vakio-public-api/assets/5529205/c4f7dccb-c9c6-4bb5-9aca-3b5690c7a352)

Вакио подключен к сети(2.4ГГц), ему присвоен адрес 192.168.0.184 – статус онлайн
 
![photo_2023-10-20 13 10 42](https://github.com/vakio-ru/vakio-public-api/assets/5529205/3555ce92-1747-4e52-af80-df8ef1afe352)

mqtt брокер установлен на локальной машине (node-red), адрес 192.168.0.229
![photo_2023-10-20 13 11 07](https://github.com/vakio-ru/vakio-public-api/assets/5529205/917c5a50-79fb-417c-a2f8-edc836334f95)

Брокер доступен с другой машины или с телефона.
При публикации событий (например изменения скорости) на третьей локальной машине (192.168.0.209) можно увидеть код сообщения. Устройство же не может подключиться к брокеру и висит в офлайне
 
![1111](https://github.com/vakio-ru/vakio-public-api/assets/5529205/2b9cbc99-ec3e-401b-9ba5-51705c074797)

ОДНАКО если подключиться к точке доступа устройства (192.168.0.1), адрес mqtt брокера изменить на 192.168.0.2 – он сразу же становится доступен и статус онлайн и все работает как надо꞉ устройство принимает/отправляет коды сообщения, можно подписаться на изменения к брокеру с 3й локальной машины.

<img width="1226" alt="Снимок экрана 2023-10-20 в 13 22 34" src="https://github.com/vakio-ru/vakio-public-api/assets/5529205/e33f1bdc-b309-4bd8-99cc-587bc7ce017c">

Внимание, вопрос꞉ можно ли подключить vakio base smart к своей локальной wifi сети чтобы отправлять/получать коды сообщений или mqtt работает только в контуре точки доступа устройства?

Может нужна дополнительная настройка роутера? Хотя я могу подключиться к брокеру с 3го компа, отправлять/получать сообщения (из консоли)

**Comment by SergeyKupavtsev** [comment]
Здравствуйте, по поводу работы в локальной сети. Можете написать, какой у Вас прибор, а так же его версию (Atmosphere и Base Smart пишут её на экрана при подключении питания), для того, чтобы воспроизвести условия у себя с аналогичным прибором и прошивкой

**Comment by kolhozz** [comment]
1.2.6 ADDA

**Comment by kolhozz** [comment]
> Здравствуйте, по поводу работы в локальной сети. Можете написать, какой у Вас прибор, а так же его версию (Atmosphere и Base Smart пишут её на экрана при подключении питания), для того, чтобы воспроизвести условия у себя с аналогичным прибором и прошивкой

я разобрался.
Пока устройство находится в режиме точки доступа - оно не коннектится к брокеру.
Когда точка доступа выключается по таймеру (15 минут) - происходит подключение.

**Comment by SergeyKupavtsev** [comment]
Наш прибор создает свою сеть, адресом 192.168.0.0 и маской сети 255.255.255.0, у Вас сеть такая же, поэтому она не может пробиться к Вам. Из-за этого и возникает ожидание, пока сеть не отключится, на данный момент исправить это не представляется возможным. Если еще остались вопросы, можно написать на почту developer@vakio.ru .
