### ISSUE TITLE
Свой MQTT + Приложение

### ISSUE THREAD

**Issue by whitevast** [vakio-ru/vakio-public-api#16]
Добрый день!
При настройке своего MQTT сервера отваливается устройство в приложении. Я так понимаю, это фича, ибо сделано через ИЛИ.
Собсна, вопрос: а не планируется ли совместное управление? Например, если я включаю свой MQTT, то прибор переключается на общение с сервером через REST API? Или вообще общение с облаком только через REST API, а MQTT - дополнительная фишка для интеграции. С одной стороны вроде бы и не надо одновременное управление при интеграции в умный дом, а с другой стороны, почему бы и нет? Бывает удобно.

**Comment by SergeyKupavtsev** [comment]
Здравствуйте, такой возможности на данный момент нет и не планируется. Прибор работает через MQTT Брокер, подключиться одновременно к 2 брокерам (своему серверу и нашему) нет возможности.
